title: DovahYol's Blog
email: zhaobing.mail@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  DovahYol's Blog
github_username:  DovahYol

encoding: UTF-8
baseurl: /blog # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed